DROP TABLE IF EXISTS kyc_review_decision CASCADE;
DROP TABLE IF EXISTS kyc_review_queue CASCADE;
DROP TABLE IF EXISTS kyc_evidence CASCADE;
DROP TABLE IF EXISTS kyc_upload CASCADE;
DROP TABLE IF EXISTS kyc_magic_email_challenge CASCADE;
DROP TABLE IF EXISTS kyc_otp_challenge CASCADE;
DROP TABLE IF EXISTS kyc_step CASCADE;
DROP TABLE IF EXISTS kyc_session CASCADE;
