//! Diesel table schema definitions.
//!
//! This file is auto-generated by `diesel print-schema` and should not be edited manually.
//! Table definitions map directly to PostgreSQL tables defined in migrations.
//!
//! Key tables:
//! - app_user: User accounts and profile data
//! - device: Device bindings with public keys
//! - flow_session: Top-level container for KYC/account sessions
//! - flow_instance: Flow executions within a session
//! - flow_step: Step executions within a flow
//! - signing_key: Backend RSA keys for token issuance

diesel::table! {
    /// Static deposit recipients synced from configuration
    app_deposit_recipients (provider, currency) {
        provider -> Text,
        full_name -> Text,
        phone_number -> Text,
        phone_regex -> Text,
        currency -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// User accounts - primary key: user_id (CUID)
    app_user (user_id) {
        user_id -> Text,
        realm -> Text,
        username -> Text,
        full_name -> Nullable<Text>,
        email -> Nullable<Text>,
        email_verified -> Bool,
        phone_number -> Nullable<Text>,
        disabled -> Bool,
        attributes -> Nullable<Jsonb>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Additional per-user dynamic data records
    app_user_data (user_id, name, data_type) {
        user_id -> Text,
        name -> Text,
        data_type -> Text,
        content -> Jsonb,
        eager_fetch -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Device bindings - composite primary key: (device_id, public_jwk)
    device (device_id, public_jwk) {
        device_id -> Text,
        user_id -> Text,
        jkt -> Text,
        public_jwk -> Text,
        device_record_id -> Text,
        status -> Text,
        label -> Nullable<Text>,
        created_at -> Timestamptz,
        last_seen_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Flow instances scoped to a session
    flow_instance (id) {
        id -> Text,
        human_id -> Text,
        session_id -> Text,
        flow_type -> Text,
        status -> Text,
        current_step -> Nullable<Text>,
        step_ids -> Jsonb,
        context -> Jsonb,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Session-level flow container
    flow_session (id) {
        id -> Text,
        human_id -> Text,
        user_id -> Nullable<Text>,
        session_type -> Text,
        status -> Text,
        context -> Jsonb,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        completed_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Atomic flow step state
    flow_step (id) {
        id -> Text,
        human_id -> Text,
        flow_id -> Text,
        step_type -> Text,
        actor -> Text,
        status -> Text,
        attempt_no -> Int4,
        input -> Nullable<Jsonb>,
        output -> Nullable<Jsonb>,
        error -> Nullable<Jsonb>,
        next_retry_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        finished_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// JWT signing keys
    signing_key (kid) {
        kid -> Text,
        private_key_pem -> Text,
        public_key_jwk -> Jsonb,
        algorithm -> Text,
        created_at -> Timestamptz,
        expires_at -> Nullable<Timestamptz>,
        is_active -> Bool,
    }
}

// Foreign key relationships
diesel::joinable!(app_user_data -> app_user (user_id));
diesel::joinable!(device -> app_user (user_id));
diesel::joinable!(flow_instance -> flow_session (session_id));
diesel::joinable!(flow_session -> app_user (user_id));
diesel::joinable!(flow_step -> flow_instance (flow_id));

diesel::allow_tables_to_appear_in_same_query!(
    app_deposit_recipients,
    app_user,
    app_user_data,
    device,
    flow_instance,
    flow_session,
    flow_step,
    signing_key,
);
