server:
  basic_auth:
    username: "authorino"
    password: "${SOME_ENV_VAR}"
  api:
    address: "0.0.0.0"
    port: 3000
    tls:
      cert_path: "./config/tls/api.crt"
      key_path: "./config/tls/api.key"
logging:
  level: "info"
database:
  url: "postgres://postgres:postgres@localhost:5432/user-storage"
  pool_size: 10
oauth2:
  jwks_url: "http://172.17.0.1:9026/realms/dev/protocol/openid-connect/certs"
