x-env: &env
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/user-storage"
  REDIS_URL: "redis://redis:6379"
  RUST_LOG: debug

services:
  app:
    build:
      context: ../..
      dockerfile: deploy/docker/user-storage/Dockerfile
    command:
      - serve
      - --config-path
      - config/dev.yaml
      - --mode
      - server
    volumes:
      - ../../config:/app/config/
    ports:
      - "3001:3000"
    environment:
      <<: *env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  app-worker:
    build:
      context: ../..
      dockerfile: deploy/docker/user-storage/Dockerfile
    command:
      - serve
      - --config-path
      - config/dev.yaml
      - --mode
      - worker
    volumes:
      - ../../config:/app/config/
    environment:
      <<: *env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
