services:
  app:
    build:
      context: ../..
      dockerfile: deploy/docker/user-storage/Dockerfile
    command:
      - serve
      - --config-path
      - config/default.yaml
    volumes:
      - ../../config:/app/config/
    ports:
      - "3001:3000"
    environment:
      REDIS_HOST: redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
