name: Setup Docker
description: Composite action that logs into GitHub Container Registry using the default workflow token.
inputs:
  app-version:
    description: Version of the application
    required: true
  image-name:
    description: Name of the image
    required: true
  registry:
    description: Version of the application
    required: false
    default: "ghcr.io"
outputs:
  annotations:
    description: Labels
    value: ${{ steps.meta.outputs.annotations }}
  labels:
    description: Labels
    value: ${{ steps.meta.outputs.labels }}
  tags:
    description: Tags
    value: ${{ steps.meta.outputs.tags }}
runs:
  using: composite
  steps:
    - name: Authenticate to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

    - id: lowercase
      name: Lowercase image name
      uses: AsZc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f
      with:
        string: ${{ inputs.image-name }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
      with:
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value={{branch}}
          type=raw,value=${{ inputs.app-version }}
          type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='Europe/Berlin'}}
          type=sha,format=long
          type=sha,format=long,prefix={{branch}}
        images: ${{ inputs.registry }}/${{ steps.lowercase.outputs.lowercase }}
